version: "3.9"
services:
  frontend:
    image: gaffko/demo_frontend:demo_v
    depends_on:
     # - processManager
      - database
     # - ndvi_0
     # - sst_0
    ports:
      - 8080:8080
    environment:
      - DOCKER=True
    volumes:
      - data-volume:/data
      
  processManager:
    image: gaffko/demo_jobmanagement:demo_v
    environment:
      - DOCKER=True
      - ndvi=ndvi_0
      - mean_sst=sst_0
      - load_collection=database
    depends_on:
      - database
      - ndvi_0
      - sst_0
 #   ports:
    #  - 80
    volumes:
      - data-volume:/data
      
  database:
    image: gaffko/demo_dataserver:demo_v
    environment:
      - DOCKER=True
  #  ports:
   #   - 80
    volumes:
      - data-volume:/data
      - data-intern:/dataintern
      
  ndvi_0:
    image: gaffko/demo_ndvi:demo_v
    environment:
      - DOCKER=True
    #depends_on:
      #- frontend
  # ports:
    #  - 80
    volumes:
      - data-volume:/data
      
  sst_0:
    image: gaffko/demo_sst:demo_v
    environment:
      - DOCKER=True
    depends_on:
      - frontend  
   # ports:
   #   - 80
    volumes:
      - data-volume:/data
      
volumes:
  data-volume:
  data-intern:
