version: "3.9"
services:
  frontend:
    image: gaffko/demo_frontend:demo_iv
    depends_on:
      - processManager
      - database
      - ndvi_0
      - sst_0
    ports:
      - 8080:8080
    environment:
      - DOCKER=True
    volumes:
      - data-volume:/data
  processManager:
    image: gaffko/demo_jobmanagement:demo_iv
    environment:
      - DOCKER=True
      - ndvi=ndvi_0
      - mean_sst=sst_0
      - load_collection=database
    depends_on:
      - database
      - ndvi_0
      - sst_0
#    ports:
 #     - 80
    volumes:
      - data-volume:/data
  database:
    image: gaffko/demo_dataserver:demo_iv
    environment:
      - DOCKER=True
 #   ports:
  #    - 80
    volumes:
      - data-volume:/data
  ndvi_0:
    image: gaffko/demo_ndvi:demo_iv
    environment:
      - DOCKER=True
#    ports:
 #     - 80
    volumes:
      - data-volume:/data
  sst_0:
    image: gaffko/demo_sst:demo_iv
    environment:
      - DOCKER=True
#    ports:
 #     - 80
    volumes:
      - data-volume:/data
volumes:
  data-volume:
