on:
 push:
    branches:
      - main

name: Backend-Validator

jobs:
  build:
    strategy:
      # this will contain a matrix of all of the combinations
      # we wish to test again:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    
    # Defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    
    # the steps that will be run through for each version and platform
    # combination
    steps:
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.CR_PAT }}
     # https://github.community/t/error-response-from-daemon-get-https-ghcr-io-v2-denied/134675/2  
     # https://docs.github.com/en/free-pro-team@latest/packages/guides/pushing-and-pulling-docker-images
        
    - name: Docker Pull and Run
      run: |
        docker pull ghcr.io/felixgi1516/geosoft2_frontend@sha256:394d8929dc6704477f5b2e6873b7d48b59f7182dac65eaba89fd5945c3779d3a
        docker run -p 80:80 -d felixgi1516/geosoft2_frontend
    # https://stackoverflow.com/questions/32046334/where-can-i-find-the-sha256-code-of-a-docker-image 
    
    # sets up go based on the version
     
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    # checks out our code locally so we can work with the files
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Clone repository
      run: | 
       git clone https://github.com/Open-EO/openeo-backend-validator.git
    - name: List Files
      run:  ls && pwd 
       
    - name: Change direcotory 
      run: |
       cd /home/runner/work/e2e_TestRepo/e2e_TestRepo/openeo-backend-validator/openeoct 
       ls && pwd
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3filter
       go get github.com/urfave/cli
       go get github.com/BurntSushi/toml
       go get github.com/mcuadros/go-version
       go build openeoct.go
       ./openeoct config /home/runner/work/e2e_TestRepo/e2e_TestRepo/config.json
        
       
    #- name: Install dependencies 
     # run: |
      #  go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3
       # go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3filter
        #go get github.com/urfave/cli
        #go get github.com/BurntSushi/toml
        #go get github.com/mcuadros/go-version
    
    #- name: Build exe
     # run: go build openeoct.exe
    
    #- name: List Files
     # run: ls && pwd

    
