on:
 push:
    branches:
      - main

name: Backend-Validator

jobs:
  build:
    strategy:
      # this will contain a matrix of all of the combinations
      # we wish to test again:
      matrix:
        go-version: [1.14.x]
            
    
    runs-on: ubuntu-latest
    
    steps:      
                
    
  
    - name: Checkout code
      uses: actions/checkout@v2  
    
    
    - name: Docker Run
      run: |
       ls && pwd
       cd /home/runner/work/TestRepo/TestRepo/
       docker-compose -f docker-compose_validator.yml up -d 
       docker-compose -f docker-compose_validator.yml logs
     #  docker-compose up -d
   #   docker run --name frontend -d -p 80:80 felixgi1516/geosoft2_frontend  
       
        
        
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}


    # checks out our code locally so we can work with the files
    
    
    - name: Clone repository
      run: | 
       git clone https://github.com/Open-EO/openeo-backend-validator.git
       git clone https://github.com/GeoSoftII2020-21/TestRepo.git
    - name: List Files
      run:  ls && pwd
     
    
       
    - name: Change directory, install dependencies and execute Validator
      run: |
       cd /home/runner/work/TestRepo/TestRepo/openeo-backend-validator/openeoct 
       ls && pwd
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3filter
       go get github.com/urfave/cli
       go get github.com/BurntSushi/toml
       go get github.com/mcuadros/go-version
       go build openeoct.go
       ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json 2>&1 | tee log_output.json
       ls -al
       grep -q 'Error' log_output.json && echo "Error found" && exit 1 || echo "No error!" && exit 0
     #< log_output.json | grep -v "Error"
        
     # < log_output.txt | grep -v "Geosoft"
     # ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json | tee validator_log.txt

    - name: Docker Stop   
      run: |
         docker stop $(docker ps -q --filter ancestor="felixgi1516/geosoft2_frontend")
         docker ps
    
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
    # user credentials
         username: ${{ secrets.EMAIL_USERNAME }}
         password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
         body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #   comma-separated string, send email to
    #   to: j_beck60@wwu.de, raabejonas@yahoo.de
    # from email name
         from: Github Action         
    
        
       
    

    
