on:
 push:
    branches:
      - main

name: Backend-Validator

jobs:
  build:
    strategy:
      # this will contain a matrix of all of the combinations
      # we wish to test again:
      matrix:
        go-version: [1.14.x]
            
    
    runs-on: ubuntu-latest
    
    steps:      
                
    
  
      
    
    
    - name: Docker Run
      run: |
       docker run --name frontend -d -p 80:80 felixgi1516/geosoft2_frontend  
       
        
        
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      
    - name: Install gron
      run: go get -u github.com/tomnomnom/gron

    # checks out our code locally so we can work with the files
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Clone repository
      run: | 
       git clone https://github.com/Open-EO/openeo-backend-validator.git
    - name: List Files
      run:  ls && pwd
     
    
       
    - name: Change directory, install dependencies and execute Validator
      run: |
       cd /home/runner/work/TestRepo/TestRepo/openeo-backend-validator/openeoct 
       ls && pwd
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3
       go get github.com/Open-EO/openeo-backend-validator/openeoct/kin-openapi/openapi3filter
       go get github.com/urfave/cli
       go get github.com/BurntSushi/toml
       go get github.com/mcuadros/go-version
       go build openeoct.go
       ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json
       content=`cat ./validator_output.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content" | grep -v "Error"
          echo $?
       
    - name: Docker Stop   
      run: |
         docker stop $(docker ps -q --filter ancestor="felixgi1516/geosoft2_frontend")
         docker ps   
        
       
    

    
