name: End to End Workflow

on: 
   push:
     branches: 
       - main
   pull_request:
     branches: 
      - main

jobs:    
       
  job1: 
   name: Trigger Job Endpoint
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2 
      
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
        python-version: 3.8
     
     - name: install xarray
       run: pip install xarray
       
     - name: install urllib3
       run: pip install urllib3  
        
     - name: install requests
       run: |
          pip install requests
          ls && pwd
          ls -a
        
     - name: read json
       id: package
       uses: juliangruber/read-file-action@v1
       with:
         path: /home/runner/work/TestRepo/TestRepo/testjob.json
       
     - name: Docker Run
       run: |
          ls && pwd
          cd /home/runner/work/TestRepo/TestRepo/
          docker-compose -f docker-compose_new.yml up -d 
          docker-compose -f docker-compose_new.yml logs
                    
          
     - name: Check endpoints
       run:  |
        docker ps -a
        curl -vv http://0.0.0.0:8080/api/v1
        docker ps -a
        docker images
         
      
     - name: Run script
       run: | 
        python e2e.py
        ls && pwd
   #    requests.get("http://0.0.0.0:80/api/v1/jobs")
    # curl -vv http://0.0.0.0:80/api/v1
