name: End to End Workflow

on: 
   push:
     branches: 
       - main
   pull_request:
     branches: 
      - main

jobs:    
       
  job1: 
   name: Trigger Job Endpoint
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2 
      
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
        python-version: 3.8
     
     - name: Install Requirements
       run: |
         pip install -r requirements.txt
         
     #- name: install xarray
     #  run: pip install xarray
       
     #- name: install urllib3
     #  run: pip install urllib3  
        
    # - name: install requests
     #  run: |
       #   pip install requests
      #    ls && pwd
       #   ls -a
          
     #- name: install netcdfF and scipy
     #  run: |
      #    pip install netCDF4
      #    pip install scipy     
          
   #  - name: install pytest
      # run: pip install pytest
    
                  
    # - name: read json
    #   id: package
    #   uses: juliangruber/read-file-action@v1
    #   with:
     #    path: /home/runner/work/TestRepo/TestRepo/testjob.json
       
     - name: Docker Run
       run: |
          ls && pwd
          cd /home/runner/work/TestRepo/TestRepo/
          docker-compose -f docker-compose_new.yml up -d 
          docker-compose -f docker-compose_new.yml logs
                    
          
     - name: Check endpoints
       run:  |
        docker ps -a
        curl -vv http://0.0.0.0:8080/api/v1
        docker ps -a
        docker images
         
      
     - name: Run SST script
       run: | 
        python e2e_sst.py
        ls && pwd
        pytest -v e2e_sst.py -k 'test_length_fin'
        
        
     - name: Run NDVI script
       env:
        username: ${{ secrets.SCIHUB_USERNAME }}
        pw: ${{ secrets.SCIHUB_PASSWORD }}
       run: | 
        python e2e_ndvi.py
        ls && pwd
        pytest -v e2e_ndvi.py -k 'test_count_fin'
        

