name: Check JS-Client

on:
  push:    
    branches:
      - main
           
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Docker Run
        run: |
         docker run --name frontend -d -p 80:80 felixgi1516/geosoft2_frontend 
      - uses: actions/checkout@v2
      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          npm install @openeo/js-client
          

