name: Check JS-Client

on:
  push:    
    branches:
      - main
           
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          npm install @openeo/js-client
          const { OpenEO } = require('@openeo/js-client');

