#@author Judith Becka, https://github.com/a2beckj
#@author Jonas Raabe, https://github.com/jona159

name: Check JS-Client

on:
  push:    
    branches:
      - main
           
jobs:
  build:
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      
      - name: Docker Run
        run: |
          ls && pwd
          cd /home/runner/work/TestRepo/TestRepo/
          docker-compose up -d
       
      - name: Setup node 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          npm install @openeo/js-client
      - uses: ./.github/actions/
      
      - name: check docker containers
        run: docker ps -a
