on:
 push:
    branches:
      - main
###
###
### THIS WORKFLOW IS CURRENTLY UNAVAILABLE FOR USAGE !!! ###
###
###
###
 
name: Check R-Client

jobs: 
  Check-R-Client:
    runs-on:  ${{ matrix.config.os }}
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          # devel is more unstable but offers more features
          - { os: ubuntu-latest, r: "devel" }
          - { os: ubuntu-latest, r: "release" }
          
    env:
      # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
     
        
      - name: Checkout Code     
        uses: actions/checkout@v2
        
      - name: Docker Run
        run: |
          ls && pwd
          cd /home/runner/work/TestRepo/TestRepo/
          docker-compose -f docker-compose.yml up -d 
          docker-compose -f docker-compose.yml logs
                    
          
      - name: Check endpoints
        run:  |
         docker ps -a
         docker ps -a
         docker images
       # curl -vv http://localhost:80/api/v1 
            
      - name: Install R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
       
      - name: Install devtools
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install curl
          R -e 'install.packages("remotes")'
          R -e 'library(remotes)'
       
      - name: Install R-Client module
        run:  R -e 'remotes::install_github(repo="Open-EO/openeo-r-client",dependencies=TRUE,force=TRUE)'
        
      - name: Execute R Script
        run:  R -e 'library(openeo); host_url="http://localhost:80/"; api_versions(host_url); gee = openeo::connect(host = host_url, version="1.0.0"); processes=list_processes(); print(names(processes))'
        
     

 
     
