on:
 push:
    branches:
      - main
      
name: Check R-Client

jobs: 
  Check-R-Client:
    runs-on:  ${{ matrix.config.os }}
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          # use a different tic template type if you do not want to build on all listed platforms
          - { os: ubuntu-latest, r: "devel" }
          - { os: ubuntu-latest, r: "release" }
          
    env:
      # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
     
      - name: Docker Run
        run: |
         docker run --name frontend -d -p 80:80 felixgi1516/geosoft2_frontend 
          
      - name: Checkout Code     
        uses: actions/checkout@v2
    
      - name: Install R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
       
      - name: Install devtools
        run: |
          conda install -c r r-devtools 
          R -e 'install.packages("rlang")'
          R -e 'install.packages("devtools")'
          R -e 'library(devtools)'
       
      - name: Install R-Client module
        run: |
         R -e 'devtools::install_github(repo="Open-EO/openeo-r-client",dependencies=TRUE, force=TRUE)'
 
     
