on:
 push:
    branches:
      - main
      
name: Check R-Client

jobs: 
  Check R-Client:
    runs-on:  ${{ matrix.config.os }}
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
          # use a different tic template type if you do not want to build on all listed platforms
          - { os: windows-latest, r: "release" }
          - { os: macOS-latest, r: "release"}
          - { os: ubuntu-latest, r: "devel" }
          - { os: ubuntu-latest, r: "release" }
          
    env:
      # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@main
        with:
          r-version: ${{ matrix.config.r }}  
