name: Unittests - Pytest Workflow

on:
  workflow_run:
    workflows: ["Update submodules"]
    branches: [main]
    types: 
      - completed
            
         
jobs:

 build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install Requirements NDVI
      run: |
         cd GeoSoftII_NDVI_Process
         pip install -r requirements.txt
    - name: Install Requirements Frontend
      run: |
         cd GeoSoftII_Frontend
         pip install -r requirements.txt
    - name: Install Requirements SST
      run: |
         cd GeoSoftII_SST_Process
         pip install -r requirements.txt
    - name: Install Requirements NDVI
      run: |
         cd GeoSoftII_NDVI_Process
         pip install -r requirements.txt
    - name: Install Requirements DataServer
      run: |
         cd GeoSoftII_DataServer
         pip install -r requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        
    - name: Install plugin
      run: pip install pytest-github-actions-annotate-failures 

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov
