#@author Judith Becka, https://github.com/a2beckj
#@author Jonas Raabe, https://github.com/jona159

name: Unittests - Pytest Workflow

on:
  workflow_run:
    workflows: ["Update submodules"]
    branches: [main]
    types: 
      - completed
            
         
jobs:

 build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true  
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install Requirements NDVI
      run: |
         cd GeoSoftII_NDVI_Process
         pip install -r requirements.txt
    - name: Install Requirements Frontend
      run: |
         cd GeoSoftII_Frontend
         pip install -r requirements.txt
    - name: Install Requirements SST
      run: |
         cd GeoSoftII_SST_Process
         pip install -r requirements.txt
    - name: Install Requirements DataServer
      run: |
         cd GeoSoftII_DataServer
         pip install -r requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        
    - name: Install plugin
      run: pip install pytest-github-actions-annotate-failures 

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov
        

    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
    # user credentials
         username: ${{ secrets.EMAIL_USERNAME }}
         password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
         body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #   comma-separated string, send email to
         to: m_busc15@uni-muenster.de , s_buse01@uni-muenster.de, m_fisc39@uni-muenster.de, a_pago03@uni-muenster.de, adrian.spork@uni-muenster.de, m_ster15@uni-muenster.de, t_walt08@uni-muenster.de, czerwas@uni-muenster.de, j_raab02@uni-muenster.de
        
    # from email name
         from: Github Action  
