name: Update_Submodules

on:
  push:
    branches:
      - main

jobs:
  event_1:
     
     runs-on: ubuntu-latest
     #if: github.event.push
     

     steps:
      - name: Update Submodule
        run: |
           git submodule init
           git submodule update
           cd GeoSoftII_NDVI_Process
           git checkout master
           git pull
           cd ..
           git add GeoSoftII_NDVI_Process
           git commit -m 'update GeoSoftII_NDVI_Process'
           git push -u origin

       
   
